project:
  type: website
  output-dir: docs

website:
  title: "Learning Azure Compute"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - topics.qmd
  sidebar:
    - title: "Home"
      style: "docked"
      background: light
      contents:
        - text: "---"
        - topics.qmd        
        - text: "---"
        - topics/hybrid-identity.qmd
        - text: "---"       
        - topics/identity-protection.qmd
        - text: "---"
        - topics/privileged-identity-management.qmd        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
